### ISSUE TITLE
S3 virge-virge dx frequency setting & brightness bug

### ISSUE THREAD

**Issue by Nemo1985** [wbcbz7/S3VBEFIX#2]
Hello i'm sorry to contact you in such uncommon way but it was the only one I could find.

I'm trying to identify the offsets in the bios of s3 cards (virge, virge dx and trio 64v+) which controls the memory and core frequency (to my knowledge they are syncro).

According to MCLK there are 3 settings to set the frequency clock, despite of that I can't find the right offsets in the bios:
[IMG]https://i.imgur.com/xF8N38f.png[/IMG]

I also found the trio64v+ full documentation (http://vgamuseum.info/index.php/cards/item/download/516_2bbbf61d0bbde9fe22086633b5908851) section 9-1 explain how the frequency is selected (pdf pages 74-75-76)

In attachment there is my bios collection, it contains bios from my virge dx cards, one with 70 mhz with the infamous bright bug (https://www.vogons.org/viewtopic.php?f=63&t=43472&start=80), the second is the bios version at 66 mhz coming from another card, the others 2 are bios I donwloaded and according to vogoners the most recent versions which have 50 mhz for memory and core).

https://drive.google.com/open?id=1agGrV13styN2YDHFP2hlAG3LW2S7CjEG

Thank you in advance for any help.

**Comment by wbcbz7** [comment]
I posted the answer in the VOGONS [thread](https://www.vogons.org/viewtopic.php?f=63&t=52617&p=817958#p817958).
Issue closed (of course, since it's rather offtopic :)
